spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    bootstrap-address: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
